# Generated by Django 6.0 on 2026-01-08 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='store',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='market.product'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
