# Generated by Django 6.0 on 2026-02-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_sellerrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerrequest',
            name='message',
        ),
        migrations.AlterField(
            model_name='sellerrequest',
            name='status',
            field=models.CharField(choices=[('В ожидании', 'В ожидании'), ('Одобрено', 'Одобрено'), ('Отклонено', 'Отклонено')], default='pending', max_length=20),
        ),
    ]
