# Generated by Django 6.0 on 2026-02-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_remove_sellerrequest_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20),
        ),
    ]
